command:
  - python
  - main.py

health_check:
  path: "/health"
  port: 8000
  initial_delay_seconds: 90  # Increased from 30
  period_seconds: 15
  timeout_seconds: 10
  failure_threshold: 5

env:
  - name: NICEGUI_HOST
    value: "0.0.0.0"
  - name: NICEGUI_PORT
    value: "8000"